### ISSUE TITLE
message_to接口中的msg消息体错误

### ISSUE THREAD

**Issue by rubyonrailsworks** [bayetech/easemob#2]
https://github.com/bayetech/easemob/blob/bf12ff37a7d41957b770386a4f6d746e1c3a55c4/lib/easemob/messages.rb#L7

此处应该是

```ruby
jd = { target_type: target_type, target: [*target],
             msg: { type: :txt, msg: text } }
```

@Eric-Guo 

环信即时通讯V2文档：http://docs.easemob.com/start/100serverintegration/50messages
环信即时通讯V3文档：http://docs.easemob.com/im/100serverintegration/50messages 

see pull request #3

**Comment by Eric-Guo** [comment]
0.3.3 版本发布了，感谢PR #3
